device_type: SHGS-1
id: SHGS-1
name: Shelly Gas
generation: devicegeneration.gen1
apis:
  settings:
    description: 'Gen1 API endpoint: settings'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_inputs: integer
        num_outputs: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      debug_enable: boolean
      allow_cross_origin: boolean
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      set_volume: integer
      eco_mode_enabled: boolean
  status:
    description: 'Gen1 API endpoint: status'
    response_structure:
      wifi_sta:
        connected: boolean
        ssid: string
        ip: string
        rssi: integer
      cloud:
        enabled: boolean
        connected: boolean
      mqtt:
        connected: boolean
      time: string
      unixtime: integer
      serial: integer
      has_update: boolean
      mac: string
      cfg_changed_cnt: integer
      actions_stats:
        skipped: integer
      gas_sensor:
        sensor_state: string
        self_test_state: string
        alarm_state: string
      concentration:
        ppm: integer
        is_valid: boolean
      valves:
      - state: '...'
      update:
        status: string
        has_update: boolean
        new_version: string
        old_version: string
        beta_version: string
      ram_total: integer
      ram_free: integer
      fs_size: integer
      fs_free: integer
      uptime: integer
  shelly:
    description: 'Gen1 API endpoint: shelly'
    response_structure:
      type: string
      mac: string
      auth: boolean
      fw: string
      discoverable: boolean
      longid: integer
      num_inputs: integer
      num_outputs: integer
  settings/actions:
    description: 'Gen1 API endpoint: settings/actions'
    response_structure:
      actions:
        alarm_off_url:
        - '...'
        alarm_mild_url:
        - '...'
        alarm_heavy_url:
        - '...'
  settings/ap:
    description: 'Gen1 API endpoint: settings/ap'
    response_structure:
      enabled: boolean
      ssid: string
      key: string
  settings/light:
    description: 'Gen1 API endpoint: settings/light'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_inputs: integer
        num_outputs: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      debug_enable: boolean
      allow_cross_origin: boolean
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      set_volume: integer
      eco_mode_enabled: boolean
  settings/login:
    description: 'Gen1 API endpoint: settings/login'
    response_structure:
      enabled: boolean
      unprotected: boolean
      username: string
  settings/mqtt:
    description: 'Gen1 API endpoint: settings/mqtt'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_inputs: integer
        num_outputs: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      debug_enable: boolean
      allow_cross_origin: boolean
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      set_volume: integer
      eco_mode_enabled: boolean
  settings/network:
    description: 'Gen1 API endpoint: settings/network'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_inputs: integer
        num_outputs: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      debug_enable: boolean
      allow_cross_origin: boolean
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      set_volume: integer
      eco_mode_enabled: boolean
  settings/relay/0:
    description: 'Gen1 API endpoint: settings/relay/0'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_inputs: integer
        num_outputs: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      debug_enable: boolean
      allow_cross_origin: boolean
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      set_volume: integer
      eco_mode_enabled: boolean
  settings/cloud:
    description: 'Gen1 API endpoint: settings/cloud'
    response_structure:
      enabled: boolean
  settings/device:
    description: 'Gen1 API endpoint: settings/device'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_inputs: integer
        num_outputs: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      debug_enable: boolean
      allow_cross_origin: boolean
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      set_volume: integer
      eco_mode_enabled: boolean
parameters:
  name:
    type: string
    description: Device name
    api: settings
    parameter_path: name
  mqtt_enable:
    type: boolean
    description: Enable MQTT
    api: settings
    parameter_path: mqtt.enable
  mqtt_server:
    type: string
    description: MQTT server address
    api: settings
    parameter_path: mqtt.server
  eco_mode:
    type: boolean
    description: Energy saving mode
    api: settings
    parameter_path: eco_mode_enabled
type_mappings:
- SHGS-1
