device_type: SHSW-PM
id: SHSW-PM
name: Shelly 1PM
generation: devicegeneration.gen1
apis:
  settings:
    description: 'Gen1 API endpoint: settings'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_outputs: integer
        num_meters: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      factory_reset_from_switch: boolean
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      led_status_disable: boolean
      debug_enable: boolean
      allow_cross_origin: boolean
      ext_switch_enable: boolean
      ext_switch_reverse: boolean
      ext_switch:
        '0':
          relay_num: '...'
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      max_power: integer
      supply_voltage: integer
      power_correction: float
      mode: string
      longpush_time: integer
      relays:
      - name: '...'
        appliance_type: '...'
        ison: '...'
        has_timer: '...'
        default_state: '...'
        btn_type: '...'
        btn_reverse: '...'
        auto_on: '...'
        auto_off: '...'
        schedule: '...'
        schedule_rules: '...'
        max_power: '...'
      ext_sensors: {}
      ext_temperature: {}
      ext_humidity: {}
      eco_mode_enabled: boolean
  status:
    description: 'Gen1 API endpoint: status'
    response_structure:
      wifi_sta:
        connected: boolean
        ssid: string
        ip: string
        rssi: integer
      cloud:
        enabled: boolean
        connected: boolean
      mqtt:
        connected: boolean
      time: string
      unixtime: integer
      serial: integer
      has_update: boolean
      mac: string
      cfg_changed_cnt: integer
      actions_stats:
        skipped: integer
      relays:
      - ison: '...'
        has_timer: '...'
        timer_started: '...'
        timer_duration: '...'
        timer_remaining: '...'
        overpower: '...'
        source: '...'
      meters:
      - power: '...'
        overpower: '...'
        is_valid: '...'
        timestamp: '...'
        counters: '...'
        total: '...'
      inputs:
      - input: '...'
        event: '...'
        event_cnt: '...'
      temperature: float
      overtemperature: boolean
      tmp:
        tC: float
        tF: float
        is_valid: boolean
      temperature_status: string
      ext_sensors: {}
      ext_temperature: {}
      ext_humidity: {}
      update:
        status: string
        has_update: boolean
        new_version: string
        old_version: string
        beta_version: string
      ram_total: integer
      ram_free: integer
      fs_size: integer
      fs_free: integer
      uptime: integer
  shelly:
    description: 'Gen1 API endpoint: shelly'
    response_structure:
      type: string
      mac: string
      auth: boolean
      fw: string
      discoverable: boolean
      longid: integer
      num_outputs: integer
      num_meters: integer
  settings/actions:
    description: 'Gen1 API endpoint: settings/actions'
    response_structure:
      actions:
        btn_on_url:
        - '...'
        btn_off_url:
        - '...'
        longpush_url:
        - '...'
        shortpush_url:
        - '...'
        out_on_url:
        - '...'
        out_off_url:
        - '...'
        lp_on_url:
        - '...'
        lp_off_url:
        - '...'
        report_url:
        - '...'
        ext_temp_over_url:
        - '...'
        ext_temp_under_url:
        - '...'
        ext_hum_over_url:
        - '...'
        ext_hum_under_url:
        - '...'
  settings/ap:
    description: 'Gen1 API endpoint: settings/ap'
    response_structure:
      enabled: boolean
      ssid: string
      key: string
  settings/light:
    description: 'Gen1 API endpoint: settings/light'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_outputs: integer
        num_meters: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      factory_reset_from_switch: boolean
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      led_status_disable: boolean
      debug_enable: boolean
      allow_cross_origin: boolean
      ext_switch_enable: boolean
      ext_switch_reverse: boolean
      ext_switch:
        '0':
          relay_num: '...'
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      max_power: integer
      supply_voltage: integer
      power_correction: float
      mode: string
      longpush_time: integer
      relays:
      - name: '...'
        appliance_type: '...'
        ison: '...'
        has_timer: '...'
        default_state: '...'
        btn_type: '...'
        btn_reverse: '...'
        auto_on: '...'
        auto_off: '...'
        schedule: '...'
        schedule_rules: '...'
        max_power: '...'
      ext_sensors: {}
      ext_temperature: {}
      ext_humidity: {}
      eco_mode_enabled: boolean
  settings/login:
    description: 'Gen1 API endpoint: settings/login'
    response_structure:
      enabled: boolean
      unprotected: boolean
      username: string
  settings/mqtt:
    description: 'Gen1 API endpoint: settings/mqtt'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_outputs: integer
        num_meters: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      factory_reset_from_switch: boolean
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      led_status_disable: boolean
      debug_enable: boolean
      allow_cross_origin: boolean
      ext_switch_enable: boolean
      ext_switch_reverse: boolean
      ext_switch:
        '0':
          relay_num: '...'
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      max_power: integer
      supply_voltage: integer
      power_correction: float
      mode: string
      longpush_time: integer
      relays:
      - name: '...'
        appliance_type: '...'
        ison: '...'
        has_timer: '...'
        default_state: '...'
        btn_type: '...'
        btn_reverse: '...'
        auto_on: '...'
        auto_off: '...'
        schedule: '...'
        schedule_rules: '...'
        max_power: '...'
      ext_sensors: {}
      ext_temperature: {}
      ext_humidity: {}
      eco_mode_enabled: boolean
  settings/network:
    description: 'Gen1 API endpoint: settings/network'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_outputs: integer
        num_meters: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      factory_reset_from_switch: boolean
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      led_status_disable: boolean
      debug_enable: boolean
      allow_cross_origin: boolean
      ext_switch_enable: boolean
      ext_switch_reverse: boolean
      ext_switch:
        '0':
          relay_num: '...'
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      max_power: integer
      supply_voltage: integer
      power_correction: float
      mode: string
      longpush_time: integer
      relays:
      - name: '...'
        appliance_type: '...'
        ison: '...'
        has_timer: '...'
        default_state: '...'
        btn_type: '...'
        btn_reverse: '...'
        auto_on: '...'
        auto_off: '...'
        schedule: '...'
        schedule_rules: '...'
        max_power: '...'
      ext_sensors: {}
      ext_temperature: {}
      ext_humidity: {}
      eco_mode_enabled: boolean
  settings/relay/0:
    description: 'Gen1 API endpoint: settings/relay/0'
    response_structure:
      name: 'null'
      appliance_type: string
      ison: boolean
      has_timer: boolean
      default_state: string
      btn_type: string
      btn_reverse: integer
      auto_on: float
      auto_off: float
      schedule: boolean
      schedule_rules: []
      max_power: integer
  settings/cloud:
    description: 'Gen1 API endpoint: settings/cloud'
    response_structure:
      enabled: boolean
  settings/device:
    description: 'Gen1 API endpoint: settings/device'
    response_structure:
      device:
        type: string
        mac: string
        hostname: string
        num_outputs: integer
        num_meters: integer
      wifi_ap:
        enabled: boolean
        ssid: string
        key: string
      wifi_sta:
        enabled: boolean
        ssid: string
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      wifi_sta1:
        enabled: boolean
        ssid: 'null'
        ipv4_method: string
        ip: 'null'
        gw: 'null'
        mask: 'null'
        dns: 'null'
      ap_roaming:
        enabled: boolean
        threshold: integer
      mqtt:
        enable: boolean
        server: string
        user: string
        id: string
        reconnect_timeout_max: float
        reconnect_timeout_min: float
        clean_session: boolean
        keep_alive: integer
        max_qos: integer
        retain: boolean
        update_period: integer
      coiot:
        enabled: boolean
        update_period: integer
        peer: string
      sntp:
        server: string
        enabled: boolean
      login:
        enabled: boolean
        unprotected: boolean
        username: string
      pin_code: string
      name: string
      fw: string
      factory_reset_from_switch: boolean
      pon_wifi_reset: boolean
      discoverable: boolean
      build_info:
        build_id: string
        build_timestamp: string
        build_version: string
      cloud:
        enabled: boolean
        connected: boolean
      timezone: string
      lat: float
      lng: float
      tzautodetect: boolean
      tz_utc_offset: integer
      tz_dst: boolean
      tz_dst_auto: boolean
      time: string
      unixtime: integer
      led_status_disable: boolean
      debug_enable: boolean
      allow_cross_origin: boolean
      ext_switch_enable: boolean
      ext_switch_reverse: boolean
      ext_switch:
        '0':
          relay_num: '...'
      actions:
        active: boolean
        names:
        - '...'
      hwinfo:
        hw_revision: string
        batch_id: integer
      max_power: integer
      supply_voltage: integer
      power_correction: float
      mode: string
      longpush_time: integer
      relays:
      - name: '...'
        appliance_type: '...'
        ison: '...'
        has_timer: '...'
        default_state: '...'
        btn_type: '...'
        btn_reverse: '...'
        auto_on: '...'
        auto_off: '...'
        schedule: '...'
        schedule_rules: '...'
        max_power: '...'
      ext_sensors: {}
      ext_temperature: {}
      ext_humidity: {}
      eco_mode_enabled: boolean
parameters:
  name:
    type: string
    description: Device name
    api: settings
    parameter_path: name
  mqtt_enable:
    type: boolean
    description: Enable MQTT
    api: settings
    parameter_path: mqtt.enable
  mqtt_server:
    type: string
    description: MQTT server address
    api: settings
    parameter_path: mqtt.server
  max_power:
    type: number
    description: Maximum power in watts
    api: settings
    parameter_path: max_power
type_mappings:
- SHSW-PM
